-- Configuración avanzada y estética para fzf-lua
return {
  "ibhagwan/fzf-lua",
  dependencies = { "nvim-tree/nvim-web-devicons" },
  config = function()
    require("fzf-lua").setup({
  "hide",
      winopts = {
        height     = 0.85,
        width      = 0.80,
        row        = 0.35,
        col        = 0.50,
        border     = "rounded",
        fullscreen = false,
        preview = {
          border     = "rounded",
          wrap       = false,
          hidden     = false,
          layout     = "flex",
          vertical   = "down:45%",
          horizontal = "right:60%",
          title      = true,
          title_pos  = "center",
          scrollbar  = "float",
          delay      = 20,
          winopts = {
            number         = true,
            relativenumber = false,
            cursorline     = true,
            signcolumn     = "no",
            foldenable     = false,
          },
        },
      },
       fzf_colors = true,
       keymap = {
         builtin = {
           ["<esc>"] = "abort",
         },
       },
files = {
      cmd = "find . -type f",
      prompt      = 'Files❯ ',
      multiprocess= true,
      git_icons   = true,
      file_icons  = true,
      color_icons = true,
      hidden      = true,
      actions     = {
        ["ctrl-s"] = require("fzf-lua").actions.file_split,
        ["ctrl-v"] = require("fzf-lua").actions.file_vsplit,
        ["ctrl-t"] = require("fzf-lua").actions.file_tabedit,
      },
      previewer   = "bat",
      formatter   = {"path.filename_first", 2},
    },
      grep = {
        prompt      = 'Rg❯ ',
        input_prompt= 'Grep For❯ ',
        multiprocess= true,
        git_icons   = true,
        file_icons  = true,
        color_icons = true,
        hidden      = false,
        previewer   = "bat",
      },
      buffers = {
        prompt      = 'Buffers❯ ',
        file_icons  = true,
        color_icons = true,
        sort_lastused = true,
        show_unloaded = true,
      },
      oldfiles = {
        prompt      = 'History❯ ',
        stat_file   = true,
      },
      colorschemes = {
        prompt      = 'Colorschemes❯ ',
        live_preview= true,
        winopts     = { height = 0.55, width = 0.30 },
      },
      keymaps = {
        prompt      = "Keymaps❯ ",
        winopts     = { preview = { layout = "vertical" } },
        show_desc   = true,
        show_details= true,
      },
      lsp = {
        prompt_postfix = '❯ ',
        file_icons     = true,
        jump1          = true,
        jump1_action   = require("fzf-lua").actions.file_edit,
        symbols = {
          symbol_style = 1,
          symbol_icons = {
            File          = "󰈙",
            Module        = "",
            Namespace     = "󰦮",
            Package       = "",
            Class         = "󰆧",
            Method        = "󰊕",
            Property      = "",
            Field         = "",
            Constructor   = "",
            Enum          = "",
            Interface     = "",
            Function      = "󰊕",
            Variable      = "󰀫",
            Constant      = "󰏿",
            String        = "",
            Number        = "󰎠",
            Boolean       = "󰨙",
            Array         = "󱡠",
            Object        = "",
            Key           = "󰌋",
            Null          = "󰟢",
            EnumMember    = "",
            Struct        = "󰆼",
            Event         = "",
            Operator      = "󰆕",
            TypeParameter = "󰗴",
          },
        },
      },
    })
  end,
}
